title: Gareth Bradleys Blog
description: garfbradaz new blog, hosted on github. Rambling about coding, running and any other of my ramblings.
theme:  jekyll-theme-minimal
logo: /assets/img/logo.png
plugins:
  - jekyll-feed
  - jekyll-sitemap


