title: Gareth Bradleys Blog
description: garfbradaz new blog, hosted on github. Rambling about coding, running and any other of my ramblings.
theme:  jekyll-theme-minimal
google_analytics: UA-130935873-1
logo: /assets/img/new.png
plugins:
  - jekyll-feed
  - jekyll-sitemap
url: "https://garfbradaz.github.io"
github: [metadata]
disqus:
    shortname: garfbradaz


